restaurant/config/routes.rb
Restaurant::Application.routes.draw do
  

  get "news_posts/index"
  resources :news do
    collection do
      get 'logout'
    end
  end

  get "avatars/index"
  resources :avatars do
    collection do
      get 'logout'
    end
  end

  get "comments/index"
  resources :comments do
    collection do
      get 'logout'
    end
  end

  get "restaurant/index"
  resources :restaurant do
    collection do
      get 'logout'
    end
  end

  get "reviews/index"
  resources :reviews do
    collection do
      get 'logout'
      get 'search'
      post 'comment'
      get 'editcomment'
      get 'deletecomment'
      post 'updatecomment'
    end
  end

  get "users/index"
  resources :users do
    collection do
      get 'login'
      get 'register'
      get 'logout'
      get 'userprofile'
      post 'newuser'
      post 'validate'
      post 'updateProfileInfo'

    end
  end
  
root 'reviews#index'

  

  

end

restaurant/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  # GET /reviews
  # GET /reviews.json
  require 'will_paginate/array' #used for combining 2 SQL request objects and paginating it properly
  def index
    #@reviews = Review.order('id desc').limit(5)
    @reviews = Review.paginate(:page => params[:page], :per_page => 5).order('id desc')
    

  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    if (session[:user_id])
      @review = Review.new
      respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @review }
      end
    else
      flash[:notice] = "Please log on to post"
      redirect_to '/reviews'
    end
  end

  # GET /reviews/1/edit
  def edit

  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render action: 'show', status: :created, location: @review }
      else
        format.html { render action: 'new' }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    if (allowAccessIfOwnerNameIsOrRankAtLeast("#{@review.poster}", 1))
      respond_to do |format|
        if @review.update(review_params)
          format.html { redirect_to @review, notice: 'Review was successfully updated.' }
          format.json { head :no_content }
        end
      end
    else
      respond_to do |format|
        format.html { render action: 'edit' }
        format.json { render json: @review.errors, status: :unprocessable_entity }
        flash[:notice] = 'You do not have permission to edit this review'

      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    if (allowAccessIfOwnerNameIsOrRankAtLeast("#{@review.poster}", 1))
      @review.destroy
      respond_to do |format|
        format.html { redirect_to reviews_url }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
      format.html { redirect_to reviews_url }
      format.json { head :no_content }
      flash[:notice] = 'You do not have permission to delete this review'
      end
    end
  end

  def comment
    Review.find(params[:id]).comments.create(params.require(:comment).permit(:date, :poster, :comment, 
      :review_id))
        redirect_to :action => "show", :id => params[:id]
  end


#Moved into Comments Controller.  Depreciated.  
=begin

  def editcomment

      
  end


  def updatecomment

    if commentToEdit = Comment.find(params[:commentid])
      if (belongsToCurrentUser("#{commentToEdit.poster}") || getAccessRank() <= 1  )
        commentToEdit.comment = "#{params[:commentText]}"
        commentToEdit.save
      else
        flash[:notice] = 'You do not have permission to edit this comment'
      end
    end
    redirect_to review_path "#{params[:reviewid]}"

  end
=end

  def deletecomment
  
    if commentToDelete = Comment.find(params[:commentid])
      if (allowAccessIfOwnerNameIsOrRankAtLeast("#{commentToDelete.poster}", 1))
        commentToDelete.destroy
      else
        flash[:notice] = 'You do not have permission to edit this comment'
      end
    end
    redirect_to :action => "show", :id => params[:reviewid]
  end



  def search
    pattern = params[:searchFor]
    pattern = "%" + pattern + "%"

    #'pattern' variable must be listed as many times as '?' is used.
    #@reviews = Review.where("title LIKE ? OR article LIKE ? OR poster LIKE ?", pattern, pattern, pattern)
    #@reviews = Review.paginate(:page => params[:page], :per_page => 5).
    #where("title LIKE ? OR article LIKE ? OR poster LIKE ?", pattern, pattern, pattern)

    @reviews = Review.where("title ILIKE ? OR article ILIKE ? OR poster ILIKE ?", pattern, pattern, pattern).order("id desc")
    @comments = Comment.where("comment ILIKE ? OR poster ILIKE ?", pattern, pattern).order("id desc")

    @search_results = @reviews + @comments
    
    #paginate combined SQL returns
    @search_results = @search_results.paginate(:page => params[:page], :per_page => 5)
  end



  def newuser
    respond_to do |format|
      user = User.new
      user.userid = params[:userid]
      user.password = params[:password]
      user.fullname = params[:fullname]
      user.email = params[:email]
      if user.save
        session[:user_id] = user.userid
        flash[:notice] = 'New User ID was successfully created.'
      else
        flash[:notice] = 'Sorry, User ID already exists.' 
      end
      format.html {redirect_to '/reviews' }   

    end
  end
#depreciated login validation/logout.  Moved to application controller level  
=begin
  def validate
  
    respond_to do |format|
      user = User.authenticate(params[:userid], params[:password])
      if user
        session[:user_id] = user.userid
        flash[:notice] = 'User successfully logged in'
      else
        flash[:notice] = 'Invalid user/password'
      end
      if session[:return_to_page] === nil
        format.html {redirect_to "/reviews"}
      else
      format.html {redirect_to "#{session[:return_to_page]}" }
      end
    end  
  end
=end
#migrated to application_controller
=begin
  def logout
    
    respond_to do |format|
      session.delete(:user_id)
      flash[:notice] = 'User successfully logged out'
      format.html {redirect_to '/avatars' }
    end
  end
=end
  def getUser
    user = session[:user_id]
    user
  end


#migrated to the application_controller
=begin
  def getUserInfo(userInfo = nil)
    userInfo = User.find_by userid: "#{userInfo}"
    if (userInfo != nil)
      userInfo
    else
      nil
    end
  end
=end



# moved to application_controller
=begin
  def belongsToCurrentUser(userid)
    if session[:user_id] === userid
      true
    else
      false
    end
  end
=end

#moved to users_controller
=begin
  def updateProfileInfo

    userInfo = getUserInfo(params[:userIdToEdit])

    if userInfo != nil
      userInfo.email = params[:emailupdate]   
      userInfo.save
    else
      nil
    end

        redirect_to userprofile_reviews_path
  end
=end






  private
    # Use callbacks to share common setup or constraints between actions.
    # Used when selecting a particular review to be displayed, edited, or deleted.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:title, :poster, :date, :article)
    end

 
end

restaurant/app/helpers/review_helper.rb
module ReviewHelper
end

restaurant/app/helpers/reviews_helper.rb
module ReviewsHelper

end

restaurant/app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class = "field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <!--<%= f.label :poster %><br>-->
    <%= f.hidden_field :poster, :value => "#{controller.getUser}" %>

  </div>
  <div class="field" type = "hidden">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :article %><br>
    <%= f.text_area :article %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

restaurant/app/views/reviews/_news.html.erb
<!--News Partial-->

<p>
    <% news = News.order('date desc').limit(2) %>
    <% for item in news %>
      <b><%= item.title %></b><br />
      <%= item.date %><br />
      <%= item.article %><br /><br />
    <% end %>
</p>

restaurant/app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

restaurant/app/views/reviews/editcomment.html.erb
<!-- old edit comments view -->
<!-- left here for educational purpose on how to create a form using 'form_tag' instead of form -->

<h2>Edit Comment:</h2>


<% commentToEdit = Comment.find(params[:commentid])%>
<% comment_id_value = commentToEdit.id %>
<% review_id = params[:reviewid].to_s %>
<br />
Comment ID: <%= commentToEdit.id %> <br /><br />
Comment Text: <%= commentToEdit.comment%> <br /><br />


<!--Display current user comment and allow for update. -->
<%= form_tag :action => :updatecomment, :commentid => "#{comment_id_value}", :reviewid => "#{review_id}" do %>


<%= text_area_tag :commentText, commentToEdit.comment %>
<br />
<br />
<%= submit_tag "Update Comment" %>
<br />
<% returnPage = review_path "#{review_id}"%>
<%= link_to 'Back', returnPage %>
<% end %> 

restaurant/app/views/reviews/index.html.erb
<!--The Main Window View -->

<table>


  <tbody>
   
    <br />  
    <h1 id="mainWindowHeader">Restaurant Reviews</h1>
    <br />
    <br />
    <% for review in @reviews %>
      <tr>
        <tr>
          <td>
            <%= link_to review.title, review %>  submitted by <%= review.poster %><br />
            <%= review.date %><br />
            <%= review.article %><br /><br />
            <div class="indexIdInfo">id Value: <%= review.id %><br/></div>
          </td>
        </tr>
        <tr>
          
          <td><%= link_to 'Show', review %>
            <% if controller.allowAccessIfOwnerNameIsOrRankAtLeast("#{review.poster}", 1) %>
              <%= link_to 'Edit', edit_review_path(review) %>
              <%= link_to 'Delete', review, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% else %>
            <% end %>
          </td>
        </tr>
      </tr>
    <% end %>
  </tbody>
</table>

<br />
<br />
<%= link_to 'New Review', new_review_path %>
<%= link_to 'RSS Feed', "reviews.rss"%> 

restaurant/app/views/reviews/logout.html.erb
<!--logout page does logout and redirects to main page-->
<!--This page is just a placeholder to allow for a link style button in the application.html.erb file
to do an action-->

restaurant/app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

restaurant/app/views/reviews/search.html.erb
<!--search results view-->


<h2>Search Results</h2>


<% for search_result in @search_results %>

  <% search_object_class = search_result.class.to_s %>

  <% if search_object_class === "Review" %>
      <br /><%= link_to search_result.title, search_result %> submitted by 
      <%= search_result.poster %><br />
      on <%= search_result.date %><br />



  <% else %>
    <br /><%= link_to "comment", search_result %> submitted by 
    <%= search_result.poster %><br />
    on <%= search_result.date %><br /> 
  <% end %>

<% end %>

restaurant/app/views/reviews/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @review.title %>
</p>
<p>
  <strong>Poster:</strong>
  <%= @review.poster %>
</p>

<p>
  <strong>Date:</strong>
  <%= @review.date %>
</p>

<p>
  <strong>Article:</strong>
  <%= @review.article %>
</p>
<% if controller.allowAccessIfOwnerNameIsOrRankAtLeast("#{@review.poster}", 1) %>
  <%= link_to 'Edit', edit_review_path(@review) %> |
  <%= link_to 'Delete', @review, method: :delete, data: { confirm: 'Are you sure?' } %> |
<% end %>
<%= link_to 'Back', reviews_path %>


<p>
   <h2>Comments:</h2>
   <% for comment in @review.comments.reverse %>
   posted by: <%= comment.poster %><br />
       on: <%= comment.date %><br />
   <%= comment.comment %><br /><br />
   <div class="indexIdInfo">
   Review ID: <%= @review.id %><br />
   Comment ID:<%= comment.id %> <br /><br />
   <%@comment_id_value = comment.id %>
   <%@review_id_value = @review.id %>
  </div>
   <!--Validate that current logged user has ownership of this post -->
     <% if controller.allowAccessIfOwnerNameIsOrRankAtLeast("#{comment.poster}", 1) %>
       <%= link_to 'Edit', edit_comment_path(comment) %> |
       <%= link_to 'Delete Comment', action: :deletecomment, :commentid => @comment_id_value, :reviewid => @review_id_value  %><br />
     <% end %>
   <% end %>

</p>
<hr />
<h2>Submit new comment:</h2>
<%= form_tag :action => 'comment', :id => @review do%>
<% if controller.userIsLoggedIn() %>
<strong><!--Poster: --></strong><%= hidden_field "comment", "poster", :value => "#{controller.getUser}"  %><br /><br />
<% else %>
<strong>Currently Not Logged In.</strong><%= hidden_field "comment", "poster", :value => "Anonymous"  %><br /><br />
<% end %>
<strong>Date: </strong><%= datetime_select "comment", "date" %><br /><br />
<strong>Comment:</strong><br />
<%= text_area "comment", "comment", :rows => 5 %><br />
<%= submit_tag "Comment" %>
<% end %>

restaurant/app/views/reviews/userprofile.html.erb
<!-- User Profile Page -->
<!--update this to allow for viewing by others.  Will need to fix how userInfo is determined -->
<!--consider adding default avatar if user has not uploaded in one -->
<% user = controller.getUser %>

<%if user != nil%>
	<% userInfo = controller.getUserInfo("#{user}") %>
	<%if userInfo != nil%>

	  <strong>Username: </strong> <%= userInfo.fullname %> <br />
	  <strong>Email: </strong> <%= userInfo.email %>
	  <br />
	  <div ><strong style="vertical-align: top">Avatar:</strong>
	  <!--Check if user has uploaed an avatar. -->
	  <% user_avatar = Avatar.find_by avatar_user_id: "#{user}" %>
	  <% if user_avatar != nil %>
	  	<%= image_tag user_avatar.avatar.url() %>
	  </div>
	  <%= link_to 'Upload New Avatar', edit_avatar_path(user_avatar) %>

	  <% else %>
	  </div>
	  <%= link_to 'Upload New Avatar', new_avatar_path() %>

	  <% end %>

	  <br />
	  <br />
	  


	  

	Update Profile

	<%= form_tag :action => :updateProfileInfo ,:userIdToEdit => "#{userInfo.userid}" do %>

	<%= label_tag :email %>
	<%= text_field_tag :emailupdate, userInfo.email %>

	<br />
	<br />
	<%= submit_tag "Update Profile" %>


	<% end %> 


	  
	<%else%>
	  <% flash[:notice] = 'Requested user not found' %>
	<%end%>



<% else %>	
	<strong><%= link_to 'Login to see user profile', {action: :login} %><br /></strong>
<% end %>



<br />
<%= link_to 'Back', reviews_path %>