restaurant/config/routes.rb
Restaurant::Application.routes.draw do
  

  get "news_posts/index"
  resources :news do
    collection do
      get 'logout'
    end
  end

  get "avatars/index"
  resources :avatars do
    collection do
      get 'logout'
    end
  end

  get "comments/index"
  resources :comments do
    collection do
      get 'logout'
    end
  end

  get "restaurant/index"
  resources :restaurant do
    collection do
      get 'logout'
    end
  end

  get "reviews/index"
  resources :reviews do
    collection do
      get 'logout'
      get 'search'
      post 'comment'
      get 'editcomment'
      get 'deletecomment'
      post 'updatecomment'
    end
  end

  get "users/index"
  resources :users do
    collection do
      get 'login'
      get 'register'
      get 'logout'
      get 'userprofile'
      post 'newuser'
      post 'validate'
      post 'updateProfileInfo'

    end
  end
  
root 'reviews#index'

  

  

end

restaurant/app/models/news.rb
class News < ActiveRecord::Base
  validates :title, :presence => true #checks for the 'title' field if filled
end

restaurant/app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]
  # GET /news
  # GET /news.json
  require 'will_paginate/array' #used for combining 2 SQL request objects and paginating it properly
  def index
    #@news_posts = News.order('id desc').limit(5)
    #keep both here due to error when will paginate tries to pluralize @news.  @news
    #allows for the the individual posts to be displayed, while @news_posts allow for
    #pagination to function properly. 
    @news_posts = News.paginate(:page => params[:page], :per_page => 5).order('id desc')
    @news = News.paginate(:page => params[:page], :per_page => 5).order('id desc')

  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/new
  def new
    if allowAccessIfUserRankAtLeast(1)
      @news = News.new
      respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @news }
      end
    else
      flash[:notice] = "Insufficient privileges"
      redirect_to '/news'
    end
  end

  # GET /news/1/edit
  def edit

  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'news was successfully created.' }
        format.json { render action: 'show', status: :created, location: @news}
      else
        format.html { render action: 'new' }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    if allowAccessIfUserRankAtLeast(1)
      respond_to do |format|
        if @news.update(news_params)
          format.html { redirect_to @news, notice: 'news was successfully updated.' }
          format.json { head :no_content }
        end
      end
    else
      respond_to do |format|
        format.html { render action: 'edit' }
        format.json { render json: @news.errors, status: :unprocessable_entity }
        flash[:notice] = 'You do not have permission to edit this news'

      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    if allowAccessIfUserRankAtLeast(1)
      @news.destroy
      respond_to do |format|
        format.html { redirect_to news_index_url }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
      format.html { redirect_to news_index_url }
      format.json { head :no_content }
      flash[:notice] = 'You do not have permission to delete this news'
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    #used when selecting a particular news element to be displayed, edited, or deleted.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:title, :date, :article)
    end

end

restaurant/app/helpers/news_helper.rb
module NewsHelper
end

restaurant/app/views/news/_form.html.erb
<%= form_for(@news) do |f| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% @news.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class = "field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field" type = "hidden">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :article %><br>
    <%= f.text_area :article %>
  </div>
  <br/>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

restaurant/app/views/news/_news_partial.html.erb
<!--News Partial-->

<p>
    <% news = News.order('date desc').limit(1) %>
    <% for item in news %>
      <b><%= item.title %></b><br />
      <%= item.date %><br />
      <%= item.article %><br /><br />
    <% end %>
</p>

<%= link_to 'More News', news_index_path %>

restaurant/app/views/news/edit.html.erb
<h1>Editing news</h1>

<%= render 'form' %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_path %>

restaurant/app/views/news/index.html.erb
<!--The Main Window View for News -->

<table>


  <tbody>
   
    <br />  
    <h1 id="mainWindowHeader">Latest News</h1>
    <br />
    <br />
    <% for newspost in @news_posts %>
      <tr>
        <tr>
          <td>
            <%= link_to newspost.title, newspost %> <br />
            <%= newspost.date %><br />
            <%= newspost.article %><br /><br />
            <div class="indexIdInfo">News ID: <%= newspost.id %></div><br />
          </td>
        </tr>
        <tr>
          
          <td><%= link_to 'Show', newspost %>
            <% if controller.allowAccessIfUserRankAtLeast(1) %>
              <%= link_to 'Edit', edit_news_path(newspost) %>
              <%= link_to 'Delete', newspost, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% else %>
            <% end %>
          </td>
        </tr>
      </tr>
    <% end %>
  </tbody>
</table>

<br />
<br />
<% if controller.allowAccessIfUserRankAtLeast(1) %>
  <%= link_to 'New newspost', new_news_path %>
<% end %>

restaurant/app/views/news/new.html.erb
<h1>New News</h1>

<%= render 'form' %>

<%= link_to 'Back', news_index_path %>

restaurant/app/views/news/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @news.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @news.date %>
</p>

<p>
  <strong>Article:</strong>
  <br />
  <%= @news.article %>
</p>

<div class="indexIdInfo">News ID: <%= @news.id %></div><br />
<% if controller.allowAccessIfUserRankAtLeast(1)  %>
  <%= link_to 'Edit', edit_news_path(@news) %>|
  <%= link_to 'Delete', @news, method: :delete, data: { confirm: 'Are you sure?' } %>|
<% end %>
<%= link_to 'Back', news_index_path %>