restaurant/config/routes.rb
Restaurant::Application.routes.draw do
  

  get "news_posts/index"
  resources :news do
    collection do
      get 'logout'
    end
  end

  get "avatars/index"
  resources :avatars do
    collection do
      get 'logout'
    end
  end

  get "comments/index"
  resources :comments do
    collection do
      get 'logout'
    end
  end

  get "restaurant/index"
  resources :restaurant do
    collection do
      get 'logout'
    end
  end

  get "reviews/index"
  resources :reviews do
    collection do
      get 'logout'
      get 'search'
      post 'comment'
      get 'editcomment'
      get 'deletecomment'
      post 'updatecomment'
    end
  end

  get "users/index"
  resources :users do
    collection do
      get 'login'
      get 'register'
      get 'logout'
      get 'userprofile'
      post 'newuser'
      post 'validate'
      post 'updateProfileInfo'

    end
  end
  
root 'reviews#index'

  

  

end

restaurant/app/models/avatar.rb
class Avatar < ActiveRecord::Base
  belongs_to :user
  has_attached_file :avatar, #:styles => { :small => "150x150>" },
                    :url  => "/assets/avatars/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/avatars/:id/:style/:basename.:extension"

  validates_attachment_presence :avatar
  validates_attachment_size :avatar, :less_than => 0.5.megabytes
  #validates_attachment_content_type :avatar, :content_type => ['image/jpeg', 'image/png']  

end

restaurant/app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  before_action :set_avatar, only: [:show, :edit, :update, :destroy]
  def index
    @avatars = Avatar.paginate(:page => params[:page], :per_page => 5).order('id desc')
  end


  # GET /avatar/1
  # GET /avatar/1.json
  def show
  end

#fix all this so that CRUD works with the Avatar class object and database

  # GET /avatar/new
  def new
    if (session[:user_id])
      @avatar = Avatar.new
      respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @avatar }
      end
    else
      flash[:notice] = "Please log on to post"
      redirect_to '/avatar'
    end
  end

  # GET /avatar/1/edit
  def edit
  end

  # POST /avatar
  # POST /avatar.json
  def create
    @avatar = Avatar.new(avatar_params)

    respond_to do |format|
      if @avatar.save
        format.html { redirect_to @avatar, notice: 'Avatar was successfully created.' }
        format.json { render action: 'show', status: :created, location: @avatar }
      else
        format.html { render action: 'new' }
        format.json { render json: @avatar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /avatar/1
  # PATCH/PUT /avatar/1.json
  def update
    respond_to do |format|
      if @avatar.update(avatar_params)
        format.html { redirect_to @avatar, notice: 'Avatar was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @avatar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /avatar/1
  # DELETE /avatar/1.json
  def destroy
    @avatar.destroy
    respond_to do |format|
      format.html { redirect_to avatar_url }
      format.json { head :no_content }
    end
  end






  private
    # Use callbacks to share common setup or constraints between actions.
    def set_avatar
      @avatar = Avatar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def avatar_params
      params.require(:avatar).permit(:avatar_user_id, :avatar_file_name, :avatar_content, :avatar_file_size, :avatar)
    end

end

restaurant/app/helpers/avatars_helper.rb
module AvatarsHelper
end

restaurant/app/views/avatars/_avatar_form.html.erb
<%= form_for @avatar, :html => { :multipart => true } do |f| %>
  <% if @avatar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@avatar.errors.count, "error") %> prohibited this avatar from being saved:</h2>

      <ul>
      <% @avatar.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <!--<%= f.label :avatar_user_id %><br>-->
    <%= f.hidden_field :avatar_user_id, :value => "#{controller.getUser}" %>


  </div>
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

restaurant/app/views/avatars/edit.html.erb
<h1>Editing review</h1>

<%= render 'avatar_form' %>

<%= link_to 'Show', @avatar %> |
<%= link_to 'Back', avatars_path %>

restaurant/app/views/avatars/index.html.erb
<h1>Avatars</h1>

<% for avatar in @avatars %>

      <tr>
        <tr>
          <td>
            <%= link_to avatar.avatar_user_id, avatar %>  table id: <%= avatar.avatar_user_id %><br />
            Avatar Created at: <%= avatar.created_at %>
            <br />
          </td>
        </tr>
        <tr>
<%= link_to 'Show', avatar %>
<br />



<% end %>

restaurant/app/views/avatars/new.html.erb
<!-- New Avatar View File -->

<h1>Add Avatar to Your Profile</h1>

<%= render 'avatar_form' %>

<%= link_to 'Back', userprofile_reviews_path %>

restaurant/app/views/avatars/show.html.erb
<p>


  <strong>User:</strong>
  <%= @avatar.avatar_user_id  %>
</p>
<p>
  <strong>Avatar ID Num:</strong>
  <%= @avatar.id  %>

</p>
  <strong>Avatar File Name:</strong>
  <%= @avatar.avatar_file_name  %>

</p>
  <strong>Avatar File Size:</strong>
  <%= @avatar.avatar_file_size  %>
</p>
  <strong>Avatar uploaded at:</strong>
  <%= @avatar.avatar_updated_at %>
</p>

Avatar:

<%= image_tag @avatar.avatar.url() %>

<br />
<br />
  <%= link_to 'Edit', edit_avatar_path(@avatar) %>|

<%= link_to 'Back', avatars_path %>