restaurant/config/routes.rb
Restaurant::Application.routes.draw do
  

  get "news_posts/index"
  resources :news do
    collection do
      get 'logout'
    end
  end

  get "avatars/index"
  resources :avatars do
    collection do
      get 'logout'
    end
  end

  get "comments/index"
  resources :comments do
    collection do
      get 'logout'
    end
  end

  get "restaurant/index"
  resources :restaurant do
    collection do
      get 'logout'
    end
  end

  get "reviews/index"
  resources :reviews do
    collection do
      get 'logout'
      get 'search'
      post 'comment'
      get 'editcomment'
      get 'deletecomment'
      post 'updatecomment'
    end
  end

  get "users/index"
  resources :users do
    collection do
      get 'login'
      get 'register'
      get 'logout'
      get 'userprofile'
      post 'newuser'
      post 'validate'
      post 'updateProfileInfo'

    end
  end
  
root 'reviews#index'

  

  

end

restaurant/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ed's Restaurant Reviews</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => false %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => false %>
  <%= csrf_meta_tags %>
</head>

<body id = "dashboardMain">
  

  <div id = "non_footer"> 
    <a href = "/" id = "header"> 
      <h1 id="headerBanner">Ed's Restaurant Reviews        
        <div id="slogan">In Search of Delicious Food</div> 
      </h1>
    </a>



    <div id='search_pane'>
      <div id='search_icon' class='button'> Search?<span class="infobox">
        Click to Expand</span>
      </div>
      <div id='search_bar_area'>
        <%= form_tag search_reviews_path , :method => 'get' do %>
        <label><font color="tan" size="-1">Search for review:</font> </label>
        <%= text_field_tag :searchFor, params[:searchFor], :class =>"search_bar", :id => "search_text_bar" %>
        <%= submit_tag "Find", :class => "search_bar", :id => "find_button" %>
        <% end %> 
      </div>
    </div>

    
    <br />
    

      <div id="content">
        <div id="navigation">
          <div class="svg-nav-decoration">
            <!-- ----------SVG Navigation Graphics--------------- -->
            <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
               width="600px" height="50px" viewBox="0 0 800 75" enable-background="new 0 0 800 75" xml:space="preserve" class="svg-nav-decoration-size">
            <g class="svg-nav-decoration-hover-area">      
              <path d="M16.382,19.208c0.607,0.324,6.177,3.626,16.221,8.715
                  C42.65,32.984,57.238,39.775,75.98,46.293c18.721,6.524,41.628,12.668,67.7,16.643c26.058,4.027,55.219,5.837,86.042,5.084
                  c30.833-0.709,63.294-3.925,96.241-8.764c32.96-4.821,66.421-11.22,99.596-17.851c33.178-6.629,66.093-13.468,98.019-19.137
                  c31.899-5.55,62.892-10.045,91.85-11.786c15.899-0.79,31.808-0.793,47.596,0.361c15.782,1.149,31.444,3.475,46.699,7.292
                  l2.854,0.732l1.374,0.363c0.203,0.049,0.39,0.118,0.585,0.176l0.723,0.224L721,21.406c3.805,1.185,7.572,2.394,11.299,3.677
                  c1.863,0.641,3.716,1.299,5.557,1.979l2.751,1.036c0.63,0.24,0.465,0.186,0.59,0.238l0.217,0.1l1.726,0.806
                  c2.293,1.089,4.551,2.228,6.765,3.423l2.801,1.745l1.054,0.66c-0.246,0.013-0.492,0.041-0.74,0.095
                  c-0.535,0.171-1.092,0.411-1.603,0.936c-0.049,0.135-0.206,0.255-0.286,0.378c-0.171,0.261-0.289,0.619-0.36,0.881
                  c-0.047,0.174-0.029,0.317-0.061,0.465c-0.011,0.048-0.053,0.062-0.057,0.101c-0.017,0.187,0.025,0.533,0.052,0.724
                  c0.013,0.089,0.046,0.159,0.062,0.253c0.003,0.014-0.032,0.031-0.027,0.05c0.099,0.398,0.317,0.787,0.618,1.187
                  c0.02,0.023,0.043-0.018,0.061,0.022c0.093,0.11,0.19,0.219,0.293,0.302c0.551,0.443,1.382,0.629,1.999,0.498
                  c0.569-0.124,1.205-0.646,1.451-1.201c0.208-0.474,0.156-1.144-0.187-1.744c-0.303-0.536-0.807-0.92-1.285-0.802
                  c0.146,0.142,0.24,0.295,0.227,0.443c-0.056,0.127-0.113,0.253-0.28,0.361c-0.26,0.083-0.588,0.058-0.771-0.287
                  c-0.259-0.482-0.008-1.149,0.563-1.293c0.141,0.008,0.298-0.049,0.402-0.057c0.235-0.018,0.432-0.017,0.644-0.002
                  c0.568,0.042,1.262,0.125,1.748,0.266l0.249,0.082c1.347,0.834,2.587,1.659,3.529,2.48l-0.036-0.017
                  c-0.361-0.14-0.653-0.199-1.01-0.254c-0.133-0.021-0.267-0.084-0.387-0.093c-0.042-0.005-0.095,0.038-0.145,0.038
                  c-0.164,0-0.32-0.028-0.498-0.005c-0.563,0.077-1.257,0.377-1.639,1.007c-0.16,0.502-0.211,1.024,0.109,1.626
                  c0.033,0.063,0.084,0.109,0.119,0.172c0.593,0.685,1.543,0.573,2.082-0.21c0.002-0.095,0.019-0.187,0.071-0.271
                  c0.019-0.388-0.407-0.958-0.755-0.892c0.112,0.091,0.16,0.135,0.146,0.275c-0.144,0.294-0.518,0.195-0.552-0.152
                  c0.095-0.336,0.333-0.522,0.681-0.655c0.141-0.054,0.285-0.052,0.44-0.074c0.207-0.029,0.409-0.081,0.594-0.067
                  c0.167,0.012,0.326,0.081,0.484,0.116c0.042,0.011,0.079,0.002,0.114,0.011c0.118,0.033,0.223,0.044,0.334,0.086
                  c0.146,0.059,0.28,0.154,0.443,0.224c0.082,0.033,0.177,0.034,0.26,0.071l0.161,0.083c0.882,1.01,1.489,2.067,1.622,3.505
                  c0.222,2.795-2.966,3.301-2.344,1.335c1.104-0.181,3.334-0.674,0.34-2.486c-1.837-0.606-2.942,1.189-3.022,3.137
                  c-0.074,1.957,0.782,4.044,3.071,4.275c3.84,0.437,4.981-4.006,3.703-6.961c-1.886-4.375-5.778-6.897-10.028-8.942
                  c2.803,0.082,5.664,1.268,7.904,3.146c2.246,1.873,3.847,4.428,4.275,7.109c0.469,2.748-0.032,6.278-2.219,8.464
                  c-2.174,2.252-2.674-1.551-1.029-0.446c0.76-1.167-0.437-1.911-1.828-1.709c-1.398,0.195-2.9,1.353-2.925,3.735
                  c-0.039,2.145,1.197,2.86,2.781,2.827c1.577-0.04,3.532-0.811,4.794-1.864c2.038-1.715,3.162-3.567,3.474-5.533
                  c0.318-1.961-0.177-4.021-1.209-5.975c-2.044-3.932-6.265-7.287-9.198-8.967c2.91,0.549,5.972,2.123,8.598,4.227
                  c2.633,2.099,4.804,4.725,6.115,7.204c1.057,1.959,1.7,4.627,1.059,6.857c-0.488,1.696-1.648,2.4-2.56,2.622
                  c-0.921,0.217-1.633-0.071-1.361-0.536c0.434-0.76,2.361,0.654,2.048-1.72c-0.342-2.144-3.509-0.712-4.717,0.329
                  c-2.835,2.395-2.497,4.648-1.056,5.687c1.462,1.039,4.194,1.076,7.037-0.893c3.153-2.213,4.688-4.543,4.781-7.085
                  c0.111-2.524-1.209-5.17-3.303-7.511c-2.089-2.35-4.923-4.372-7.663-5.935c-2.742-1.572-5.383-2.706-7.138-3.511l0.401-0.064
                  c2.631,0.549,5.394,0.865,8.176,0.973c3.32,1.558,5.578,4.46,7.281,7.781c1.712,3.331,2.868,7.059,4.176,10.54
                  c0.74,1.969,2.132,3.495,3.296,5.162c1.16,1.646,2.085,3.444,1.709,5.423c-0.408,2.092-1.272,3.623-3.586,4.93
                  c-2.052,0.922-3.434,0.723-4.009,0.354c-0.572-0.376-0.383-1.055,0.799-1.254c0.347,0.416-0.261,0.44-0.129,0.757
                  c1.064,0.226,2.021-0.43,2.396-1.317c0.383-0.875,0.158-1.956-0.878-2.173c-1.799-0.372-3.389,0.421-4.586,1.456
                  c-1.188,1.047-2.04,2.311-2.254,3.253c0.439,0.972,1.348,1.47,2.65,1.775c1.295,0.295,2.971,0.377,4.793,0.26
                  c3.646-0.22,7.909-1.39,10.631-3.458c3.618-2.698,5.433-6.188,5.652-9.857c0.234-3.667-1.136-7.43-3.471-10.638
                  c-2.332-3.229-5.584-5.9-9.057-7.969c-3.479-2.084-7.174-3.6-10.607-4.876c2.305,0.048,4.47-0.58,6.722-1.112
                  c1.949-0.464,3.967-1.342,5.162-2.714c1.191-1.365,1.542-3.281,0.032-5.671c0.825-1.949,1.229-4.109-0.335-6.339
                  c-1.861-2.648-5.109-3.217-7.079-1.423c-0.761,1.166-0.873,2.169-0.072,3.521c0.527,0.875,3.169,2.578,2.692,0.461
                  c-1.346,0.009-0.599-0.96,0.146-1.141c1.434,0.962,1.188,2.069,0.321,3.271l-0.021,0.031c-2.139,2.965-4.351,4.971-6.537,6.284
                  v-0.002c0.021-0.274-0.056-0.495-0.054-0.729c0-0.076,0.066-0.102,0.059-0.164c-0.035-0.294-0.23-0.824-0.345-1.117
                  c-0.055-0.136-0.137-0.241-0.199-0.383c-0.01-0.021,0.043-0.054,0.028-0.082c-0.321-0.601-0.848-1.172-1.532-1.727
                  c-0.043-0.032-0.065,0.035-0.113-0.023c-0.205-0.151-0.418-0.299-0.63-0.403c-1.136-0.564-2.633-0.632-3.596-0.243
                  c-0.885,0.354-1.662,1.355-1.791,2.266c-0.108,0.779,0.286,1.758,1.083,2.552c0.71,0.707,1.647,1.15,2.374,0.851
                  c-0.29-0.178-0.497-0.385-0.534-0.614c0.04-0.206,0.082-0.411,0.309-0.619c0.387-0.19,0.937-0.235,1.364,0.25
                  c0.455,0.513,0.46,1.249,0.063,1.725c-3.973,1.13-7.895,0.332-11.943-1.373l0.058,0.004c0.622,0.03,1.095-0.014,1.668-0.094
                  c0.215-0.03,0.451,0.003,0.64-0.033c0.067-0.013,0.127-0.098,0.203-0.118c0.253-0.07,0.509-0.094,0.771-0.202
                  c0.831-0.341,1.782-1.047,2.076-2.12c0.004-0.803-0.185-1.6-1.036-2.364c-0.089-0.08-0.195-0.128-0.288-0.207
                  c-1.354-0.773-2.82-0.18-3.199,1.208c0.053,0.138,0.079,0.28,0.047,0.427c0.198,0.567,1.173,1.205,1.682,0.962
                  c-0.226-0.087-0.325-0.129-0.379-0.34c0.062-0.494,0.71-0.508,0.951-0.013c0.03,0.532-0.249,0.904-0.719,1.246
                  c-0.19,0.139-0.415,0.197-0.645,0.298c-0.305,0.134-0.588,0.301-0.878,0.365c-0.261,0.057-0.545,0.034-0.804,0.057
                  c-0.07,0.006-0.123,0.036-0.18,0.039c-0.199,0.01-0.364,0.043-0.556,0.036c-0.253-0.01-0.512-0.08-0.799-0.097
                  c-0.142-0.008-0.286,0.039-0.433,0.029l-0.268-0.034c-0.622-0.304-1.249-0.622-1.876-0.957l-2.637-1.27l-5.768-1.787l-2.89-0.863
                  l-1.447-0.424l-0.724-0.211l-3.892-1.355c-5.86-1.998-11.8-3.773-17.78-5.485l-4.493-1.286c-0.777-0.223-1.441-0.425-2.191-0.593
                  l-2.257-0.542c-3.014-0.709-6.043-1.353-9.081-1.953c-12.156-2.386-24.487-3.915-36.874-4.721
                  c-24.788-1.625-49.745-0.437-74.549,2.155c-12.408,1.3-24.792,2.951-37.158,4.805c-6.183,0.926-12.361,1.901-18.539,2.907
                  c-6.152,0.996-12.321,2.107-18.479,3.21c-55.689,9.755-114.188,22.76-171.604,31.769c-28.697,4.515-57.12,8.021-84.586,9.829
                  c-27.46,1.828-53.958,1.927-78.605,0.155c-24.648-1.74-47.414-5.362-67.45-10.136c-20.049-4.758-37.358-10.62-51.458-16.294
                  c-14.109-5.675-25.041-11.106-32.589-15.075c-7.545-3.986-11.742-6.479-12.259-6.763C11.79,11.203,5.79,8.604,5.091,9.699
                  C4.402,10.775,9.361,15.185,16.382,19.208z"/>
            </svg>
            <!--------------End SVG Navigation Graphics -------------------->
          </div>

          <div id="navigation_elements_panel">

            <% user = controller.getUser %>
              
              <%if user != nil%>
                
                <strong> Hello, <%= user %> </strong>
                <strong><%= link_to 'User Profile', userprofile_users_path , 
                { :action => :userprofile, :class => 
                  " navigation_element 
                  #{controller.linkMatchesCurrentPage(userprofile_users_path)}"}  %>
                </strong>
                <strong><%= link_to 'Logout', { :action => :logout}, :class => 
                "navigation_element"  %></strong>
              <%elsif user === nil%>
                <strong><%= link_to 'Login to Post', login_users_path, :class => 
                "navigation_element 
                #{controller.linkMatchesCurrentPage(login_users_path)}"  %>
                </strong>
              <%else%>
              <%end%>

            <% if controller.allowAccessIfUserRankAtLeast(1) %>
              <strong><%= link_to 'Post News', new_news_path ,{ :class =>
                "navigation_element 
                #{controller.linkMatchesCurrentPage(new_news_path)}"} %>
              </strong>
            <% end %>


            <strong><%= link_to 'Sign Up', register_users_path, :class => 
            "navigation_element 
            #{controller.linkMatchesCurrentPage(register_users_path)}"  %>
            </strong>
            <strong><%= link_to 'Post a New Review', new_review_path, :class => 
            "navigation_element 
            #{controller.linkMatchesCurrentPage(new_review_path)}"  %>
            </strong>
            <strong><%= link_to 'View Reviews', reviews_path, :class => 
            "navigation_element 
            #{controller.linkMatchesCurrentPage(reviews_path)}"  %>
            </strong>
          </div>
        </div>
      </div>


      <div id="main_panel">
        <p style="color: orange"><%= flash[:notice] %></p>
        <%= yield %><!-- the 'yield' will yield to the code located in the index.html.erb file 
        within the current directory for the site.  Thus, if this is for the reviews/index, then yield will
        yield to the code located within reviews/index.html.erb.  If it is accessed by
        restaurant/index, then it will yield to the code located in the restaurant/index.html.erb code.-->
      </div>
      <div id="news">
        <div id="news_pull_tab" class='button'>
          <div id="news_pull_tab_text">News</div>
          <span class="infobox">
          Click to Toggle
          </span>
        </div>
        <div id="news_content">
        <h2>What's cookin'</h2><br />
          The latest restaurant news<br />
          <%= render( :partial => "news/news_partial") %>
        </div>
      </div>
    </div>

    <div id="pagination_panel">
      <% if @reviews != nil || @comments != nil || @news_posts != nil || @users != nil || @avatars != nil %>
        <%= will_paginate @search_results, :previous_label => '&#8592; Prev 5', :next_label => 'Next 5 &#8594;' %>
      <% end %>
    </div>
  </div>

  <div id="footer" >
    <a href="mailto:myuser@myhost.com" class="footer_text" id="contact_us_link">Contact Us</a>
    <font size="1" class="footer_text"> | &copy;2014 Edmund Wong </font>
    <br />

    <% footer_image = "/assets/images/banner.jpg" %>
    <% footer_image2 = "/assets/images/banner2.jpg" %>
    <% footer_image_text = "NoImageFound" %>



    <div class="f1_container">
      <div class="f1_card" class="shadow">
        <div class="front face">
            <%=image_tag "#{footer_image}"%>
        </div>

        <div class="back face center">
            <%=image_tag "#{footer_image2}"%>
        </div>
      </div>
    </div>
  </div> 


</body>
</html>
    